/*
    DM360 Evaluation Software

    (c)Texas Instruments 2007
*/

#include <csl_rsz.h>


CSL_Status CSL_rszHwReset(CSL_RszHandle hndl)
{
  if (hndl == NULL)
    return CSL_EFAIL;

  hndl->regs->GCK_MMR = 1;
  hndl->regs->GCK_SDR = 1;  

  hndl->regs->SRC_EN = CSL_RSZ_SRC_EN_RESETVAL;
  hndl->regs->SRC_MODE = CSL_RSZ_SRC_MODE_RESETVAL;
  hndl->regs->SRC_FMT0 = CSL_RSZ_SRC_FMT0_RESETVAL;
  hndl->regs->SRC_FMT1 = CSL_RSZ_SRC_FMT1_RESETVAL;
  hndl->regs->SRC_VPS = CSL_RSZ_SRC_VPS_RESETVAL;
  hndl->regs->SRC_VSZ = CSL_RSZ_SRC_VSZ_RESETVAL;
  hndl->regs->SRC_HPS = CSL_RSZ_SRC_HPS_RESETVAL;
  hndl->regs->SRC_HSZ = CSL_RSZ_SRC_HSZ_RESETVAL;
  hndl->regs->DMA_RZA = CSL_RSZ_DMA_RZA_RESETVAL;
  hndl->regs->DMA_RZB = CSL_RSZ_DMA_RZB_RESETVAL;
  hndl->regs->DMA_STA = CSL_RSZ_DMA_STA_RESETVAL;
  hndl->regs->RESERVED0 = CSL_RSZ_RESERVED0_RESETVAL;
  hndl->regs->IRQ_RZA = CSL_RSZ_IRQ_RZA_RESETVAL;
  hndl->regs->IRQ_RZB = CSL_RSZ_IRQ_RZB_RESETVAL;
  hndl->regs->YUV_Y_MIN = CSL_RSZ_YUV_Y_MIN_RESETVAL;
  hndl->regs->YUV_Y_MAX = CSL_RSZ_YUV_Y_MAX_RESETVAL;
  hndl->regs->YUV_C_MIN = CSL_RSZ_YUV_C_MIN_RESETVAL;
  hndl->regs->YUV_C_MAX = CSL_RSZ_YUV_C_MAX_RESETVAL;
  hndl->regs->YUV_PHS = CSL_RSZ_YUV_PHS_RESETVAL;
  hndl->regs->SEQ = CSL_RSZ_SEQ_RESETVAL;
  hndl->regs->RZA_EN = CSL_RSZ_RZA_EN_RESETVAL;
  hndl->regs->RZA_MODE = CSL_RSZ_RZA_MODE_RESETVAL;
  hndl->regs->RZA_420 = CSL_RSZ_RZA_420_RESETVAL;
  hndl->regs->RZA_I_VPS = CSL_RSZ_RZA_I_VPS_RESETVAL;
  hndl->regs->RZA_I_HPS = CSL_RSZ_RZA_I_HPS_RESETVAL;
  hndl->regs->RZA_O_VSZ = CSL_RSZ_RZA_O_VSZ_RESETVAL;
  hndl->regs->RZA_O_HSZ = CSL_RSZ_RZA_O_HSZ_RESETVAL;
  hndl->regs->RZA_V_PHS_Y = CSL_RSZ_RZA_V_PHS_Y_RESETVAL;
  hndl->regs->RZA_V_PHS_C = CSL_RSZ_RZA_V_PHS_C_RESETVAL;
  hndl->regs->RZA_V_DIF = CSL_RSZ_RZA_V_DIF_RESETVAL;
  hndl->regs->RZA_V_TYP = CSL_RSZ_RZA_V_TYP_RESETVAL;
  hndl->regs->RZA_V_LPF = CSL_RSZ_RZA_V_LPF_RESETVAL;
  hndl->regs->RZA_H_PHS = CSL_RSZ_RZA_H_PHS_RESETVAL;
  hndl->regs->RZA_H_PHS_ADJ = CSL_RSZ_RZA_H_PHS_ADJ_RESETVAL;
  hndl->regs->RZA_H_DIF = CSL_RSZ_RZA_H_DIF_RESETVAL;
  hndl->regs->RZA_H_TYP = CSL_RSZ_RZA_H_TYP_RESETVAL;
  hndl->regs->RZA_H_LPF = CSL_RSZ_RZA_H_LPF_RESETVAL;
  hndl->regs->RZA_DWN_EN = CSL_RSZ_RZA_DWN_EN_RESETVAL;
  hndl->regs->RZA_DWN_AV = CSL_RSZ_RZA_DWN_AV_RESETVAL;
  hndl->regs->RZA_RGB_EN = CSL_RSZ_RZA_RGB_EN_RESETVAL;
  hndl->regs->RZA_RGB_TYP = CSL_RSZ_RZA_RGB_TYP_RESETVAL;
  hndl->regs->RZA_RGB_BLD = CSL_RSZ_RZA_RGB_BLD_RESETVAL;
  hndl->regs->RZA_SDR_Y_BAD_H = CSL_RSZ_RZA_SDR_Y_BAD_H_RESETVAL;
  hndl->regs->RZA_SDR_Y_BAD_L = CSL_RSZ_RZA_SDR_Y_BAD_L_RESETVAL;
  hndl->regs->RZA_SDR_Y_SAD_H = CSL_RSZ_RZA_SDR_Y_SAD_H_RESETVAL;
  hndl->regs->RZA_SDR_Y_SAD_L = CSL_RSZ_RZA_SDR_Y_SAD_L_RESETVAL;
  hndl->regs->RZA_SDR_Y_OFT = CSL_RSZ_RZA_SDR_Y_OFT_RESETVAL;
  hndl->regs->RZA_SDR_Y_PTR_S = CSL_RSZ_RZA_SDR_Y_PTR_S_RESETVAL;
  hndl->regs->RZA_SDR_Y_PTR_E = CSL_RSZ_RZA_SDR_Y_PTR_E_RESETVAL;
  hndl->regs->RZA_SDR_C_BAD_H = CSL_RSZ_RZA_SDR_C_BAD_H_RESETVAL;
  hndl->regs->RZA_SDR_C_BAD_L = CSL_RSZ_RZA_SDR_C_BAD_L_RESETVAL;
  hndl->regs->RZA_SDR_C_SAD_H = CSL_RSZ_RZA_SDR_C_SAD_H_RESETVAL;
  hndl->regs->RZA_SDR_C_SAD_L = CSL_RSZ_RZA_SDR_C_SAD_L_RESETVAL;
  hndl->regs->RZA_SDR_C_OFT = CSL_RSZ_RZA_SDR_C_OFT_RESETVAL;
  hndl->regs->RZA_SDR_C_PTR_S = CSL_RSZ_RZA_SDR_C_PTR_S_RESETVAL;
  hndl->regs->RZA_SDR_C_PTR_E = CSL_RSZ_RZA_SDR_C_PTR_E_RESETVAL;
  hndl->regs->RZB_EN = CSL_RSZ_RZB_EN_RESETVAL;
  hndl->regs->RZB_MODE = CSL_RSZ_RZB_MODE_RESETVAL;
  hndl->regs->RZB_420 = CSL_RSZ_RZB_420_RESETVAL;
  hndl->regs->RZB_I_VPS = CSL_RSZ_RZB_I_VPS_RESETVAL;
  hndl->regs->RZB_I_HPS = CSL_RSZ_RZB_I_HPS_RESETVAL;
  hndl->regs->RZB_O_VSZ = CSL_RSZ_RZB_O_VSZ_RESETVAL;
  hndl->regs->RZB_O_HSZ = CSL_RSZ_RZB_O_HSZ_RESETVAL;
  hndl->regs->RZB_V_PHS_Y = CSL_RSZ_RZB_V_PHS_Y_RESETVAL;
  hndl->regs->RZB_V_PHS_C = CSL_RSZ_RZB_V_PHS_C_RESETVAL;
  hndl->regs->RZB_V_DIF = CSL_RSZ_RZB_V_DIF_RESETVAL;
  hndl->regs->RZB_V_TYP = CSL_RSZ_RZB_V_TYP_RESETVAL;
  hndl->regs->RZB_V_LPF = CSL_RSZ_RZB_V_LPF_RESETVAL;
  hndl->regs->RZB_H_PHS = CSL_RSZ_RZB_H_PHS_RESETVAL;
  hndl->regs->RZB_H_PHS_ADJ = CSL_RSZ_RZB_H_PHS_ADJ_RESETVAL;
  hndl->regs->RZB_H_DIF = CSL_RSZ_RZB_H_DIF_RESETVAL;
  hndl->regs->RZB_H_TYP = CSL_RSZ_RZB_H_TYP_RESETVAL;
  hndl->regs->RZB_H_LPF = CSL_RSZ_RZB_H_LPF_RESETVAL;
  hndl->regs->RZB_DWN_EN = CSL_RSZ_RZB_DWN_EN_RESETVAL;
  hndl->regs->RZB_DWN_AV = CSL_RSZ_RZB_DWN_AV_RESETVAL;
  hndl->regs->RZB_RGB_EN = CSL_RSZ_RZB_RGB_EN_RESETVAL;
  hndl->regs->RZB_RGB_TYP = CSL_RSZ_RZB_RGB_TYP_RESETVAL;
  hndl->regs->RZB_RGB_BLD = CSL_RSZ_RZB_RGB_BLD_RESETVAL;
  hndl->regs->RZB_SDR_Y_BAD_H = CSL_RSZ_RZB_SDR_Y_BAD_H_RESETVAL;
  hndl->regs->RZB_SDR_Y_BAD_L = CSL_RSZ_RZB_SDR_Y_BAD_L_RESETVAL;
  hndl->regs->RZB_SDR_Y_SAD_H = CSL_RSZ_RZB_SDR_Y_SAD_H_RESETVAL;
  hndl->regs->RZB_SDR_Y_SAD_L = CSL_RSZ_RZB_SDR_Y_SAD_L_RESETVAL;
  hndl->regs->RZB_SDR_Y_OFT = CSL_RSZ_RZB_SDR_Y_OFT_RESETVAL;
  hndl->regs->RZB_SDR_Y_PTR_S = CSL_RSZ_RZB_SDR_Y_PTR_S_RESETVAL;
  hndl->regs->RZB_SDR_Y_PTR_E = CSL_RSZ_RZB_SDR_Y_PTR_E_RESETVAL;
  hndl->regs->RZB_SDR_C_BAD_H = CSL_RSZ_RZB_SDR_C_BAD_H_RESETVAL;
  hndl->regs->RZB_SDR_C_BAD_L = CSL_RSZ_RZB_SDR_C_BAD_L_RESETVAL;
  hndl->regs->RZB_SDR_C_SAD_H = CSL_RSZ_RZB_SDR_C_SAD_H_RESETVAL;
  hndl->regs->RZB_SDR_C_SAD_L = CSL_RSZ_RZB_SDR_C_SAD_L_RESETVAL;
  hndl->regs->RZB_SDR_C_OFT = CSL_RSZ_RZB_SDR_C_OFT_RESETVAL;
  hndl->regs->RZB_SDR_C_PTR_S = CSL_RSZ_RZB_SDR_C_PTR_S_RESETVAL;
  hndl->regs->RZB_SDR_C_PTR_E = CSL_RSZ_RZB_SDR_C_PTR_E_RESETVAL;

  return CSL_SOK;
}
